### ISSUE TITLE
Не логинится

### ISSUE THREAD

**Issue by nipolnp** [LTD-Beget/sprutio#118]
Доброго времени!

Очень странный баг.
Пытаюсь исправить уже 2 дня (по нескольку раз переустанавливаю весь софт и сервак).
Запускаю новый сервак, на нем Debian и есть 2 пользователя: root и default.
Пользователь root может логиниться в Sprutio, а default - нет.
Для пользователя default при нажатии кнопки "Войти" Sprutio "задумывается" на несколько секунд и ничего не происходит, снова активируется кнопка "Войти".
Причем по SFTP оба пользователя заходят нормально.
Огромная просьба помочь, т.к. без Вашего мегасофта как без рук.
До этого все работало на многих аналогичных серваках без проблем.
Заранее благодарю!

Ошибки которые нашел:

в app.log:
-----------------------------
AuthHandler.py[LINE:92]# ERROR    [2023-09-05 13:00:25,647] -- app -- In AuthHandler Exception: 'NoneType' object has no attribute 'get'
BaseHandler.py[LINE:57]# ERROR    [2023-09-05 13:00:25,648] -- app -- Handled exception in app.py: HTTP 403: Forbidden (Authentication Failed)Traceback:Traceback (most recent call last):
  File "/app/handlers/AuthHandler.py", line 70, in post
    session_token = FMAuth.authenticate_by_pam(self, login, password)
  File "/app/classes/core/FMAuth.py", line 19, in authenticate_by_pam
    if not answer.get('Error', False) and answer.get('data').get('status', False):
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 212, in catch
    return method(*args, **kwargs)
  File "/app/handlers/AuthHandler.py", line 93, in post
    raise tornado.web.HTTPError(403, "Authentication Failed")
tornado.web.HTTPError: HTTP 403: Forbidden (Authentication Failed)
BaseHandler.py[LINE:61]# ERROR    [2023-09-05 13:00:25,649] -- app -- login: None -- Traceback:Traceback (most recent call last):
  File "/app/handlers/AuthHandler.py", line 70, in post
    session_token = FMAuth.authenticate_by_pam(self, login, password)
  File "/app/classes/core/FMAuth.py", line 19, in authenticate_by_pam
    if not answer.get('Error', False) and answer.get('data').get('status', False):
AttributeError: 'NoneType' object has no attribute 'get'
-----------------------------

в rpc.log:
-----------------------------
pyportal: handler.py          #86  : fm-rpc:DEBUG  [2023-09-05 13:00:23,121][160]  [id:713a43e6] Handler: 
  Route: 'main/authenticate'
  Arguments: {b'login': b'default', b'password': b'PASS_HERE'}
pyportal: handler.py          #135 : fm-rpc:DEBUG  [2023-09-05 13:00:23,122][160]  [id:713a43e6] FrontController: 
  module controller: controllers.main_controller
  class controller: MainController
  action in controller: authenticate
pyportal: controller.py       #51  : fm-rpc:DEBUG  [2023-09-05 13:00:23,123][160]  [id:713a43e6] Controller: 
  action name: action_authenticate
  arguments to action: {'login': b'default', 'password': b'PASS_HERE'}
pyportal: controller.py       #64  : fm-rpc:INFO   [2023-09-05 13:00:23,123][160]  [id:713a43e6] Exec: MainController.action_authenticate({'login': b'default', 'password': b'PASS_HERE'})
pyportal: main_controller.py  #72  : fm-rpc:DEBUG  [2023-09-05 13:00:25,640][161]  [id:713a43e6] Process on_error() data: {'error': True,
 'message': 'Not Authenticated - 7 (Authentication failure) '
            '("default":"PASS_HERE"):',
 'traceback': 'Traceback (most recent call last):\n'
              '  File "/rpc/lib/FileManager/workers/main/Authenticate.py", '
              'line 12, in run\n'
              '    self.preload()\n'
              '  File "/rpc/lib/FileManager/workers/baseWorkerCustomer.py", '
              'line 37, in preload\n'
              "    raise Exception('Not Authenticated - %s (%s) "
              '("%s":"%s"):\' % (p.code, p.reason, self.login, '
              'self.password))\n'
              'Exception: Not Authenticated - 7 (Authentication failure) '
              '("default":"PASS_HERE"):\n'}
pyportal: main_controller.py  #101 : fm-rpc:INFO   [2023-09-05 13:00:25,645][160]  [id:713a43e6] Process on_finish()
pyportal: main_controller.py  #102 : fm-rpc:INFO   [2023-09-05 13:00:25,646][160]  [id:713a43e6] Process exit code 0 info = <Authenticate(Authenticate-1, stopped)>
pyportal: handler.py          #77  : fm-rpc:DEBUG  [2023-09-05 13:00:25,646][160]  [id:713a43e6] Request completed in seconds: 2.526996612548828
-----------------------------

**Comment by Zigoreks** [comment]
Нашлось решение?
