### ISSUE TITLE
Проблема с загрузкой файла

### ISSUE THREAD

**Issue by redcap52** [LTD-Beget/sprutio#56]
при загрузке файла через Sprut.io выскакивает ошибка FileManager Server Error

Проблема возникает только при загрузке файлов извне
при создании папок и файлов проблемы нет - всё работает

```
pyportal: start.sendfile.py #211 : fm-rpc:INFO [2017-01-19 17:39:58,267][289] Server handle_accept()
pyportal: start.sendfile.py #52 : fm-rpc:INFO [2017-01-19 17:39:58,268][289] Handler __init__()
pyportal: start.sendfile.py #106 : fm-rpc:INFO [2017-01-19 17:39:58,268][289] FileStreamHandler init()
pyportal: start.sendfile.py #114 : fm-rpc:INFO [2017-01-19 17:39:58,269][289] FileStreamHandler handle_read()
pyportal: start.sendfile.py #77 : fm-rpc:ERROR [2017-01-19 17:39:58,269][289] Handler handle_error()
pyportal: start.sendfile.py #239 : fm-rpc:INFO [2017-01-19 17:39:59,403][338] Starting server
pyportal: start.sendfile.py #249 : fm-rpc:INFO [2017-01-19 17:39:59,406][338] LISTEN {'logger_name': '/var/log/fm/sendfile.log', 'host': '0.0.0.0', 'port': 51600}
```
вот что появляется в sendfile.log при попытке загрузить файл
app.log
```
BaseHandler.py[LINE:55]# ERROR [2017-01-19 17:39:58,287] — app — Handled exception in app.py: [Errno 104] Connection reset by peerTraceback:Traceback (most recent call last):
File "/app/handlers/BaseHandler.py", line 204, in catch
return method(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
return method(self, *args, **kwargs)
File "/app/handlers/UploadHandler.py", line 62, in post
sent = sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer

BaseHandler.py[LINE:67]# ERROR [2017-01-19 17:39:58,290] — app — login:root — Traceback:Traceback (most recent call last):
File "/app/handlers/BaseHandler.py", line 204, in catch
return method(*args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
return method(self, *args, **kwargs)
File "/app/handlers/UploadHandler.py", line 62, in post
sent = sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```
Лог ошибок веб-сервера (error.log):
`2017/01/19 17:39:52 [warn] 8#8: *348 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000006, client: 176.213.12.245, server: , request: "POST /upload?session=%7B%22host%22%3A%22localhost%22%2C%22path%22%3A%22%2Fopt%2Fsprutio%2Flogs%22%2C%22is_share%22%3Afalse%2C%22is_share_write%22%3Afalse%2C%22type%22%3A%22home%22%7D&overwrite=false HTTP/1.1", host: "188.120.251.147:9443", referrer: "https://188.120.251.147:9443/"`

**Comment by kirvesp** [comment]
@redcap52 Здравствуйте, обновите сборки спрутио. Если ошибка будет повторяться -- отпишитесь сюда и приложите снова логи.

**Comment by redcap52** [comment]
rpc.log:
```
 'message': '[Errno 2] No such file or directory: '
            "'/tmp/fm/kaynovacp/upload/1486886474'",
 'traceback': 'Traceback (most recent call last):\n'
              '  File "/rpc/lib/FileManager/workers/local/uploadFile.py", '
              'line 18, in run\n'
              '    self._prepare()\n'
              '  File "/rpc/lib/FileManager/workers/baseUploadWorker.py", '
              'line 19, in _prepare\n'
              '    os.lchown(os.path.dirname(self.file_path), pw.pw_uid, '
              'pw.pw_gid)\n'
              'FileNotFoundError: [Errno 2] No such file or directory: '
              "'/tmp/fm/kaynovacp/upload/1486886474'\n"}
```

**Comment by kirvesp** [comment]
@redcap52 какие права выставлены для директории ```downloads```, она находится в том же месте, откуда производилась установка спрутио?

**Comment by redcap52** [comment]
Нет, она находится в другом месте. На папку, куда производится загрузка, стоят права 755

**Comment by kirvesp** [comment]
Проблема в создании директорий для загрузки и выставлении прав на них
