### ISSUE TITLE
Перестали отображаться файлы в панелях

### ISSUE THREAD

**Issue by shadowlmd** [LTD-Beget/sprutio#74]
Перестали отображаться файлы в панелях, внизу надпись "Loading..." , в app.log такие ошибки:
```
BaseHandler.py[LINE:57]# ERROR    [2017-11-04 16:06:30,362] -- app -- Handled exception in app.py: 'path'Traceback:Traceback (most recent call last):
  File "/app/handlers/BaseHandler.py", line 212, in catch
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/tornado/web.py", line 2743, in wrapper
    return method(self, *args, **kwargs)
  File "/app/handlers/actions/main/RestoreSessionHandler.py", line 14, in post
    response = action.run()
  File "/app/modules/home/actions/main/restore_session.py", line 16, in run
    same_path = (session['Right']['path'] == session['Left']['path'])
KeyError: 'path'
```
Докеры работают:
```
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                           NAMES
d71b4bba165f        beget/sprutio-nginx   "nginx -g 'daemon off"   2 days ago          Up 2 days           127.0.0.1:9080->80/tcp, 0.0.0.0:9443->443/tcp   sprutio_nginx_1
9b27c932296b        beget/sprutio-app     "/init"                  2 days ago          Up 2 days                                                           sprutio_app_1
bdc7473c53e3        beget/sprutio-rpc     "/init"                  2 days ago          Up 2 days                                                           sprutio_rpc_1
654a9b0bc964        redis:3.0             "docker-entrypoint.sh"   2 days ago          Up 2 days           6379/tcp                                        sprutio_redis_1
cab9bc6d6523        beget/sprutio-cron    "/init"                  2 days ago          Up 2 days                                                           sprutio_cron_1
```
Ubuntu 16.04, всё свежее, руками ничего не трогал, сломалось само.

**Comment by shadowlmd** [comment]
<s>Есть предположение, что это случилось после того, как я зашёл по ссылке https://my.server:9443/login и залогинился, хотя до этого не разлогинивался.</s>

Нет, на другом аккаунте не воспроизвелось. Кстати, да, проблема только с одним аккаунтом. В других браузерах, в инкогнито, без разницы.

**Comment by shadowlmd** [comment]
Починилось нажатием кнопки "Home server", после этого левая панель перерисовалась, а после обновления страницы нарисовались обе панели.
